Initial CentOS5 support.

diff --git a/scripts/install_matrix_deps b/scripts/install_matrix_deps
--- a/scripts/install_matrix_deps
+++ b/scripts/install_matrix_deps
@@ -7,57 +7,49 @@ if grep -q '^CentOS release 5\.' /etc/redhat-release; then
 	os=centos5
 fi
 
-. ./yum_config_$os
-
-if [[ -f /etc/init.d/iptables ]]; then
-	# Turn the firewall off (it's just a dev VM after all...)
-	/etc/init.d/iptables stop
-	chkconfig iptables off
-fi
-
-proxyline=""
-if ! [[ -z $proxy ]]; then
-	proxyline="proxy=$proxy"
-fi
-
-# Configure hosts file
-if ! grep -q '^# Hosts configured by Vagrant' /etc/hosts; then
-	{
-		echo
-		echo "# Hosts configured by Vagrant"
-		echo "127.0.0.1 smpcontent.dev sitemigrator.dev"
-	} >> /etc/hosts
+# Install Squiz Package repository if missing
+if ! [[ -f /etc/yum.repos.d/squiz.repo ]]; then
+	if [[ $os == 'sl6' ]]; then
+		rpm -Uvh http://packages.squiz.net/scientific/6/noarch/squiz-repo-0.3-0-squiz.noarch.rpm
+	else
+		rpm -Uvh http://packages.squiz.net/centos/5/noarch/squiz-repo-0.1-3-squiz.noarch.rpm
+	fi
 fi
 
 # List out any rpms we need to install
 rpms=(
-	# direct matrix deps
-	httpd
-	php{,-{ldap,cli,pgsql,gd,soap,xml,mysql,mbstring,pear}}
-	zlib-devel pcre-devel tidy antiword poppler-utils
-	
-	# We're using postgres as the db
-	postgresql{,-contrib,-server}
-
 	# cvs used for the matrix checkout.sh script
 	cvs
 
 	# used during template generation/restoration
 	rsync
+
+	# regular matrix deps
+	httpd
 )
 
 if [[ $os == 'sl6' ]]; then
-	rpms+=(php-pspell)
+	# Scientific Linux 6 requirements
+	rpms+=(
+		# direct matrix deps
+		php{,-{ldap,cli,pgsql,gd,soap,xml,mysql,mbstring,pear,pspell}}
+		zlib-devel pcre-devel tidy antiword poppler-utils
+		
+		# We are using postgres as the db
+		postgresql{,-contrib,-server}
+	)
+else
+	# CentOS 5 requirements
+	rpms+=(
+		# direct matrix deps
+		php53{,-{ldap,cli,pgsql,gd,soap,xml,mysql,mbstring,pspell}}
+		zlib-devel pcre-devel tidy antiword poppler-utils
+		
+		# We are using postgres as the db
+		postgresql84{,-contrib,-server}
+	)
 fi
 
-# same for pear packages
-pears=(
-	Auth_SASL HTTP{,_Client,_Request} I18N_UnicodeNormalizer
-	Image_Canvas-0.3.3 Image_Color Image_Color MDB2 Mail Mail_Mime Mail_Queue
-	Mail_mimeDecode Math_Stats Net_SMTP Net_Socket Net_URL Numbers_Roman
-	SOAP-0.12.0 Services_JSON Text_Diff XML_HTMLSax XML_Parser
-	image_graph-0.8.0 
-)
 
 echo "Checking for missing rpm packages"
 # install rpm packages that are missing
@@ -72,6 +64,31 @@ if [[ ${#missing[@]} -gt 0 ]]; then
 	yum install -y "${missing[@]}"
 fi
 
+# PEAR was failing under CentOS5, so here we check if it's managed to install and install
+# it manually if it's missing
+if ! [[ $(type -t pear) == 'file' ]]; then
+	rm -f go-pear.phar
+	wget http://pear.php.net/go-pear.phar
+	# Unfortunately go-pear.phar is coded by drunk monkeys who like to press keys manually.
+	# So we use expect...
+	yum install -y expect
+	expect << EOF
+		spawn php go-pear.phar
+		expect "1-11, 'all' or Enter to continue:"
+		send "\r"
+		expect eof
+EOF
+fi
+
+# pear packages
+pears=(
+	Auth_SASL HTTP{,_Client,_Request} I18N_UnicodeNormalizer
+	Image_Canvas-0.3.3 Image_Color MDB2 Mail Mail_Mime Mail_Queue
+	Mail_mimeDecode Math_Stats Net_SMTP Net_Socket Net_URL Numbers_Roman
+	SOAP-0.12.0 Services_JSON Text_Diff XML_HTMLSax XML_Parser
+	image_graph-0.8.0 
+)
+
 # Put in a default timezeone for php to mute fairly pointless error under EL6.x:
 #     PHP Warning:  date(): It is not safe to rely on the system's timezone settings.
 php -r '$z = date_default_timezone_get(); echo "date.timezone=$z\n";' \
@@ -79,26 +96,18 @@ php -r '$z = date_default_timezone_get(); echo "date.timezone=$z\n";' \
 
 echo "Checking for missing PEAR packages"
 missing=()
-# TODO: pear proxy seems to break with ACNG (pear sends https traffic towards a http only proxy)...
-# pear config-set http_proxy "$proxy"
 for pear in "${pears[@]}"; do
 	if ! pear info "$pear" > /dev/null; then
 		missing+=("channel://pear.php.net/$pear")
 	fi
 done
 if [[ ${#missing[@]} -gt 0 ]]; then
-	# pear in centos5 is kinda out of date
-	if [[ $os == "centos5" ]]; then
-		pear upgrade -f pear
-	fi
-	echo "Installing PEAR packages: ${missing[@]}"
 	pear channel-update pear.php.net
 	pear install "${missing[@]}"
 fi
 
-# Installing phpunit for SMP testing, it needs a separate channel.
+# Installing phpunit
 if ! pear list -c phpunit | egrep -q '^PHPUnit '; then
-	echo "Installing PHPUnit"
 	# channel-discover might return non-zero exit
 	pear channel-discover pear.phpunit.de || true
 	pear channel-discover pear.symfony.com || true
@@ -109,9 +118,9 @@ fi
 if [[ templates/apache-unversioned-include.conf -nt /etc/httpd/conf.d/unversioned-include.conf ]]; then
 	echo "Configuring Apache"
 	mkdir -p /etc/httpd/conf/unversioned-sites
-    cp -f templates/apache-unversioned-include.conf /etc/httpd/conf.d/unversioned-include.conf
-    service httpd restart
-    chkconfig httpd on
+	cp -f templates/apache-unversioned-include.conf /etc/httpd/conf.d/unversioned-include.conf
+	service httpd restart
+	chkconfig httpd on
 fi
 
 if [[ ! -f /var/lib/pgsql/data/.success ]]; then
